version: '3.5'

services:
  proxy:
    image: nginx:alpine
    container_name: proxy
    volumes: 
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports: 
      - 80:80
  frontend:
    build: example-frontend/.
    container_name: frontend
  backend:
    build: example-backend/.
    container_name: backend
    environment: 
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DATABASE=postgres  
    depends_on:
      - db
  redis:
    image: 'redis:alpine'
    container_name: redis
  db:
    image: postgres:13.2-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: example
    container_name: db_postgres
    
