name: Deploy to Heroku

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build, push and Deploy to Heroku
      uses: jctaveras/heroku-deploy@v1.0.0 #akhileshns/heroku-deploy@v3.12.12
      with:
        api_key: ${{ secrets.HEROKU_API_KEY }}
        app_name: "ex31-vmtorn"
        email: "vtorniko@gmail.com"
